### ISSUE TITLE
Failed to resolve: com.github.ifmvo:TogetherAd:lastVersion

### ISSUE THREAD

**Issue by fuyouasdf** [ifmvo/TogetherAd#1]
Failed to resolve: com.github.ifmvo:TogetherAd:lastVersion

**Comment by ifmvo** [comment]
implementation 'com.github.ifmvo:TogetherAd:lastVersion'
1.2.6  替换 lastVersion
implementation 'com.github.ifmvo:TogetherAd:1.2.6'

**Comment by ifmvo** [comment]
@fuyouasdf

**Comment by fuyouasdf** [comment]
thanks,it works
