### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Chexian1** [ifmvo/TogetherAd#11]
大哥，我建议你弄个java版本的，学习成本太高了，一人血书在线等！

**Comment by ifmvo** [comment]
哈哈，java调用没问题的，kotlin、java通用，使用文档可以写个java的

**Comment by ifmvo** [comment]
哈哈，java调用没问题的，kotlin、java通用，使用文档可以写个java的

**Comment by Chexian1** [comment]
不是，java调用kotlin要进行设置，坑太多。你就整个Java的呗，大家还没与时俱进到都是kotlin吧

**Comment by ifmvo** [comment]
看大家呼声吧，全翻译一遍工作量也不少，你也可以参与翻译

**Comment by Chexian1** [comment]
AS不是可以kotlin转java么，但是只能参考，主要是我不懂kotlin。坐等楼主的文档，感谢。

**Comment by ifmvo** [comment]
应该看得懂的

**Comment by ZhouSilverBullet** [comment]
> 大哥，我建议你弄个java版本的，学习成本太高了，一人血书在线等！

老哥，今年你出去找工作，没kotlin都不好找了，基本要看得懂kotlin才要
