### ISSUE TITLE
求助，配置项目的混淆

### ISSUE THREAD

**Issue by ifmvo** [ifmvo/TogetherAd#16]

**Comment by ifmvo** [comment]
3.0.8（2020.07.09）及以上

资源库自带混淆规则，无需手动添加

**Comment by virtual-kpax** [comment]
尝试扩展了一下，增加小米的广告，使用 mimo_sdk 1.6.2，在 demo 里进行测试的时候，遇到了 `Program type already present: com.bytedance.embedapplog.AppLog` 这个看着是和 csj 有冲突？我看在 demo build.gradle 的 dependencies 里加 configurations 好像也不是，不知道怎么解决这个问题
