### ISSUE TITLE
穿山甲信息流广告使用原生渲染一直提示40029

### ISSUE THREAD

**Issue by benxin123** [ifmvo/TogetherAd#17]
请求失败了：错误码: 40029}, 错误信息：两种情况：1. SDK版本低；使用的sdk版本过低，还不支持个性化模板渲染功能。解决办法：升级到平台最新版本sdk。2. 接口使用错误；创建的代码位类型是模板渲染/非模板渲染，但是请求方法是非模板渲染/模板渲染的方法。解决办法：使用模板渲染的方法去请求模板渲染类型或者使用非模板渲染的方法去请求非模板类型的广告，如果代码位在平台上是模板渲染，可以参考文档中个性化模板XX广告的部分，demo中参考带有express部分的代码。如果代码位不是模板渲染，则不要调用含有express字样的接口。参考文档：https://partner.oceanengine.com/doc?id=5dd0fe716b181e00112e3eb8

什么情况？

**Comment by ifmvo** [comment]
调用的api 和 穿山甲后台配置的广告ID 类型不一致（ 例：你的ID是模板渲染，而调用的API是非模板渲染 ）

**Comment by benxin123** [comment]
我调用的是AdHelperNative，那应该调用哪个?

**Comment by benxin123** [comment]
3.X求更新前贴和插屏

**Comment by ifmvo** [comment]
> 3.X求更新前贴和插屏

在2.x中的前贴其实就是原生自渲染的包装，在3.x中可以使用AdHelperNative加自定义NativeTemple来实现，近期我会提供示例

**Comment by ifmvo** [comment]
> 我调用的是AdHelperNative，那应该调用哪个?

使用AdHelperNative，你创建的广告位ID必须是原生自渲染的广告位

**Comment by benxin123** [comment]
现在穿山甲好像没办法创建原生自渲染的了，我的所有广告点开都只有模板渲染

**Comment by SuperZhouyong** [comment]
激励广告也更新了，需要楼主支援

请求失败-onAdFailed  VideoFragmentcsj-----错误码: 40029, 错误信息：两种情况：1. SDK版本低；使用的sdk版本过低，还不支持个性化模板渲染功能。解决办法：升级到平台最新版本sdk。2. 接口使用错误；创建的代码位类型是模板渲染/非模板渲染，但是请求方法是非模板渲染/模板渲染的方法。解决办法：使用模板渲染的方法去请求模板渲染类型或者使用非模板渲染的方法去请求非模板类型的广告，如果代码位在平台上是模板渲染，可以参考文档中个性化模板XX广告的部分，demo中参考带有express部分的代码。如果代码位不是模板渲染，则不要调用含有express字样的接口。参考文档：https://partner.oceanengine.com/doc?id=5dd0fe716b181e00112e3eb8
