### ISSUE TITLE
广点通自渲染视频点击后返回声音依旧存在

### ISSUE THREAD

**Issue by benxin123** [ifmvo/TogetherAd#19]
广点通自渲染视频点击后进入广告详情页后再返回声音依旧存在，再次点击视频广告无法唤起广告详情页。

**Comment by ifmvo** [comment]
![image](https://user-images.githubusercontent.com/14008627/89246411-a5216600-d63d-11ea-9732-504cb2e52897.png)

自渲染使用AdHelperNativePro 替换，并按照文档处理原生广告的生命周期即可
