### ISSUE TITLE
关于广点通

### ISSUE THREAD

**Issue by TextX666888** [ifmvo/TogetherAd#2]
请问一下，知道怎么修改广点通的广告背景，比如说，APP有夜间模式以及其他颜色的主题，但是广点通的广告背景一直是白色背景，可以修改成其他颜色吗，有人说新建广告位的时候可以设置背景。但是假如APP的颜色主题有几十种，那不是要几十个广告位吗?请问大佬有研究过修改广告背景的方法吗

**Comment by ifmvo** [comment]
广点通的广告有背景吗？它就是一张图片的，图片中存在各种各样的颜色，这图片貌似不存在主题颜色这个说法。

你说后台新建广告位可以设置背景，这个我没试过不太清楚，但是我猜也就是根据你设置的颜色，广告通给你返回和这个颜色相近的图片。

所以我觉得中技术角度没法解决这个问题，就像根据手机套的颜色处理app的主题颜色一样

**Comment by ifmvo** [comment]
@TextX666888

**Comment by ifmvo** [comment]
![image](https://user-images.githubusercontent.com/14008627/56884638-f9ce4c80-6a9c-11e9-8609-d66d21eff488.png)
我觉得就像腾讯视频一样，虽然他处于夜间模式，但是中间有一个彩色的图片这不冲突的

**Comment by TextX666888** [comment]
@ifmvo 好的。谢谢！
