### ISSUE TITLE
使用原生自渲染伪装成开屏来代替广点通自己的开屏广告   广点通的话应该申请哪一种广告位

### ISSUE THREAD

**Issue by shooe** [ifmvo/TogetherAd#21]

**Comment by ifmvo** [comment]
原生自渲染

**Comment by shooe** [comment]
![image](https://user-images.githubusercontent.com/13506395/93078046-5f37d300-f6bc-11ea-85d4-ed8a2fe4ec0c.png)
动态信息流下得原生自渲染么？
E/TogetherAd: gdt: 请求失败了：错误码: 6000, 错误信息：未知错误，详细码：100133
2020-09-14 18:56:56.676 6464-6464/translate.uyghur.hash1 E/SplashAdsActivity: onAdFailed: gdt: 错误码: 6000, 错误信息：未知错误，详细码：100133
报这么错误代码

**Comment by ifmvo** [comment]
https://developers.adnet.qq.com/backend/error_code.html

广点通文档上没有100113这个错误码，建议问下广点通的客服
