### ISSUE TITLE
广点通图片全屏显示差一截子

### ISSUE THREAD

**Issue by benxin123** [ifmvo/TogetherAd#22]
用的NativeViewGdtSimple1，视频显示正常，就图片差一截子。
视频截图：https://p.pstatp.com/origin/fec90003648c411a3ed0
图片截图：https://p.pstatp.com/origin/138290001f668cf51def8

**Comment by ifmvo** [comment]
去看 NativeViewGdtSimple1 里面的布局就是写死的高度
