### ISSUE TITLE
开屏原生混合使用，广点通部分闪退

### ISSUE THREAD

**Issue by shooe** [ifmvo/TogetherAd#23]
![image](https://user-images.githubusercontent.com/13506395/93469880-b4295280-f923-11ea-9c17-2089ab5f3bba.png)

**Comment by ifmvo** [comment]
版本？，升级版本试下

**Comment by shooe** [comment]
建议出个各个平台  创建广告位的教程。我接入进来老提示广告位id与代码不匹配

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 陈序员 <notifications@github.com>
发送时间: Tuesday, October 13, 2020 4:28:01 PM
收件人: ifmvo/TogetherAd <TogetherAd@noreply.github.com>
抄送: Hash1 <shooe@live.com>; Author <author@noreply.github.com>
主题: Re: [ifmvo/TogetherAd] 开屏原生混合使用，广点通部分闪退 (#23)


Closed #23<https://github.com/ifmvo/TogetherAd/issues/23>.

―
