### ISSUE TITLE
混淆问题

### ISSUE THREAD

**Issue by benxin123** [ifmvo/TogetherAd#24]
在创建的纯净新项目(kotlin androidx)里，只有一个引导页和mainActivity里使用的demo里的混淆之后发现广点通一直初始化失败，把gdt csj core里的混淆在单独加进去之后还是初始化失败，最后我把
```
   //穿山甲（ 头条 ）
    implementation 'com.matthewchen.togetherad:csj:3.1.8-3.2.5.1'
    
    //优量汇（ 腾讯广点通 ）
    implementation 'com.matthewchen.togetherad:gdt:3.1.8-4.270.1140'
```
改用implementation project
   ```
 implementation project(':csj')
    implementation project(':gdt')
```
然后广点通初始成功了，不知道为什么会这样子

**Comment by ifmvo** [comment]
没明白你说的，加qq群沟通一下吧

**Comment by benxin123** [comment]
直接引用`implementation 'com.matthewchen.togetherad:gdt:3.1.8-4.270.1140'`混淆会有问题导致广点通初始失败，需要把项目拉到本地去implementation project(':gdt')，这样子混淆就不会出现问题，广点通是可以初始化成功的

**Comment by ifmvo** [comment]
3.2.3版本已修复
