### ISSUE TITLE
原生自渲染 广点通部分闪退

### ISSUE THREAD

**Issue by shooe** [ifmvo/TogetherAd#25]
![image](https://user-images.githubusercontent.com/13506395/96582906-85c9d900-130e-11eb-81c7-bc71d22651d9.png)

**Comment by ifmvo** [comment]
上面的报错日志不用理会
下面的报错会崩溃吗？看起来是没有再主线程请求广告的原因，请求广告必须在主线程

**Comment by shooe** [comment]
就是import的你在github上的demo

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 陈序员<mailto:notifications@github.com>
发送时间: 2020年10月22日 14:08
收件人: ifmvo/TogetherAd<mailto:TogetherAd@noreply.github.com>
抄送: Hash1<mailto:shooe@live.com>; Author<mailto:author@noreply.github.com>
主题: Re: [ifmvo/TogetherAd] 原生自渲染 广点通部分闪退 (#25)


上面的报错日志不用理会
下面的报错会崩溃吗？看起来是没有再主线程请求广告的原因，请求广告必须在主线程

―

**Comment by ifmvo** [comment]
是否必现崩溃？提供一下机型、系统版本、复现步骤

**Comment by shooe** [comment]
崩溃百分之50会复现，具体为SplashHybridActivity，  机型华为nova 5i-pro。复现步骤（想看看广点通的开屏广告样式，因为是三家随机请求，就一直点到随机到广点通）  然后会崩溃 IDE提示（com.ifmvo.togetherad.core.custom.flow. DefaultImageLoader类中loadImage下val inputStream = conn.inputStream）



[cid:image001.png@01D6A8EE.0A372FC0]

发件人: 陈序员<mailto:notifications@github.com>
发送时间: 2020年10月22日 14:17
收件人: ifmvo/TogetherAd<mailto:TogetherAd@noreply.github.com>
抄送: Hash1<mailto:shooe@live.com>; Author<mailto:author@noreply.github.com>
主题: Re: [ifmvo/TogetherAd] 原生自渲染 广点通部分闪退 (#25)


是否必现崩溃？提供一下机型、系统版本、复现步骤

―
