### ISSUE TITLE
穿山甲广告取消了 自渲染的模板。请求广告报 40029

### ISSUE THREAD

**Issue by SuperZhouyong** [ifmvo/TogetherAd#26]
1. 错误信息
请求失败-onAdFailed VideoFragmentcsj-----错误码: 40029, 错误信息：两种情况：1. SDK版本低；使用的sdk版本过低，还不支持个性化模板渲染功能。解决办法：升级到平台最新版本sdk。2. 接口使用错误；创建的代码位类型是模板渲染/非模板渲染，但是请求方法是非模板渲染/模板渲染的方法。解决办法：使用模板渲染的方法去请求模板渲染类型或者使用非模板渲染的方法去请求非模板类型的广告，如果代码位在平台上是模板渲染，可以参考文档中个性化模板XX广告的部分，demo中参考带有express部分的代码。如果代码位不是模板渲染，则不要调用含有express字样的接口。参考文档：https://partner.oceanengine.com/doc?id=5dd0fe716b181e00112e3eb8
2. 希望楼主先优化一下 穿山甲 的模板广告渲染。

3.增进意见 
   希望楼主，对所有广告平台的模板依赖做个保底，自渲染作为 可选项目。

**Comment by SuperZhouyong** [comment]
@ifmvo 大佬希望早点解决穿山甲这个  没有自渲染的功能啊。或者能开源一下....我自己改一点点也好

**Comment by SuperZhouyong** [comment]
@ifmvo @smsrocky 可以见一个意见群，更加方便后期维护和提意见哈

**Comment by SuperZhouyong** [comment]
@ifmvo @smsrocky 大佬大概啥时候可以改啊，比较着急用，

**Comment by ifmvo** [comment]
1：本项目并不支持自渲染模板广告
2：本项目是支持信息流自渲染广告的。github项目肯定是开源的
3：项目主页下面有QQ群的二维码

**Comment by SuperZhouyong** [comment]
但是 csj 的广告现在只有模板渲染了，不支持 自渲染的信息流。你应该说反了，项目 广点通，和 穿山甲，目前是只支持  自渲染的，不支持模板渲染..... @ifmvo @smsrocky

**Comment by SuperZhouyong** [comment]
@ifmvo 谢谢楼主，解决了。之前没注意到源码，以为你混淆了。谢谢开源
