### ISSUE TITLE
激励广告也更新了，需要楼主支援

### ISSUE THREAD

**Issue by sdfwds4** [ifmvo/TogetherAd#27]
激励广告也更新了，需要楼主支援

请求失败-onAdFailed  VideoFragmentcsj-----错误码: 40029, 错误信息：两种情况：1. SDK版本低；使用的sdk版本过低，还不支持个性化模板渲染功能。解决办法：升级到平台最新版本sdk。2. 接口使用错误；创建的代码位类型是模板渲染/非模板渲染，但是请求方法是非模板渲染/模板渲染的方法。解决办法：使用模板渲染的方法去请求模板渲染类型或者使用非模板渲染的方法去请求非模板类型的广告，如果代码位在平台上是模板渲染，可以参考文档中个性化模板XX广告的部分，demo中参考带有express部分的代码。如果代码位不是模板渲染，则不要调用含有express字样的接口。参考文档：https://partner.oceanengine.com/doc?id=5dd0fe716b181e00112e3eb8

_Originally posted by @SuperZhouyong in https://github.com/ifmvo/TogetherAd/issues/17#issuecomment-713611204_

**Comment by sdfwds4** [comment]
激励广告。
使用最新的3.2.3版。
使用3.2.3里的demo的广告id，可以出现广告视频；使用自己的广告id，提示上面的错误。

**Comment by DaChao007** [comment]
同问 使用“信息流广告”展示与一楼同样的问题。 但是不出现广告 请求失败

还有一个问题：
使用 ”插屏广告“：csj: 请求失败了：错误码: 40022}, 错误信息：媒体在平台上申请的代码位“是否原生”属性与代码中使用的接口不匹配。例如：1. 媒体在平台上选择的是个性化模板banner广告的话，Android代码中请参考BannerExpressActivity进行调用；iOS代码中请参考BUDExpressBannerViewController进行调用。2. 媒体在平台上选择的是个性化模板插屏广告的话，代码中请参考InteractionExpressActivity进行调用；iOS代码位中请参考BUDExpressInterstitialViewController进行调用。PS：模板广告会带有express字样标识。

**Comment by ifmvo** [comment]
![image](https://user-images.githubusercontent.com/14008627/97517988-44ea5800-19d1-11eb-9a49-af22a49e0351.png)
![image](https://user-images.githubusercontent.com/14008627/97517996-4a47a280-19d1-11eb-975a-53e0672b8efd.png)
从穿山甲的Demo中可以看到激励广告分为两种，1：普通激励广告。2：模板激励广告。

至于为什么有两种我想应该是： 穿山甲新开通账户只能创建模板类型以提高广告展示的规范。

上面的错误日志说的很明白：ID的类型和请求方式不一致（ 模板类型的激励广告ID使用普通激励的请求方式 ）

目前TogetherAdDemo中使用的就是普通激励广告ID和普通激励广告的请求方式，如果你填入模板类型的激励ID，就会报错。

解决方法：将TogetherAd中CsjProvider中请求激励广告的方式改为模板激励广告。
详细请[查看文档](https://github.com/ifmvo/TogetherAd/blob/master/doc/extend.md)。文档中只对Banner进行举例。激励、插屏同理。

**Comment by SuperZhouyong** [comment]
我这边改好了。就是  csjprider 里面改一下。原项目 只支持 自渲染的 激励视频，和 csj 开放给我们的 模板渲染不是一样的。需要改成模板请求的接口取调用。 目前我这边是 改了就显示正确了。改动很小的，可以放心改

**Comment by SuperZhouyong** [comment]
还有，我更新了 项目中的 sdk 了。必须得更新成最新的。应该没有其他问题了 @sdfwds4

**Comment by ifmvo** [comment]
我后面计划，给穿山甲写两个Provider。一个是CsjProvider、一个是CsjExpressProvider，初始化时可以任选其一

**Comment by SuperZhouyong** [comment]
@ifmvo 可以的，其实很多广告，可以再 支持一点。框架 sdk  初始化，文件 xml 都支持很好的，点赞

**Comment by sdfwds4** [comment]
我这边也改好了，谢谢你们！
