### ISSUE TITLE
关于广告

### ISSUE THREAD

**Issue by KotlinLan** [ifmvo/TogetherAd#3]
你好，请问一下，这种方式封装，会影响计费吗?想用到线上生产环境，不知道可不可靠！感谢！

**Comment by ifmvo** [comment]
你好，开发TogetherAd也是用于我们公司的实际项目，我公司的多个项目也在同时使用，你说的影响计费是哪方面呢？

**Comment by KotlinLan** [comment]
就是说广告展示，广告点击这些，会不会影响广告商那边进行统计。

**Comment by ifmvo** [comment]
不会

**Comment by KotlinLan** [comment]
@ifmvo 你好，请问一下，如果所有广告位id是服务器下发的，应该怎么初始化？

**Comment by KotlinLan** [comment]
![image](https://user-images.githubusercontent.com/50512101/63480900-e74da800-c4bd-11e9-833f-ec6b4e5a21ff.png)
闪屏广告会出现这个内存泄漏

**Comment by ifmvo** [comment]
你的版本号是多少？

**Comment by KotlinLan** [comment]
我昨天下载的源码包进行依赖的，应该是最新版

**Comment by ifmvo** [comment]
哦哦，好的，我会尽快处理的

**Comment by KotlinLan** [comment]
@ifmvo 好的，对了腾讯开屏广告的跳过按钮，好像是支持自定义Textview，希望增加这个功能.

**Comment by ifmvo** [comment]
`SplashAD(Activity activity, ViewGroup container, View skipView, String appId, String posId, SplashADListener adListener, int fetchDelay) `

**你可以在请求广告通开屏的时候自己设置skipVIew**

**Comment by KotlinLan** [comment]
内存泄漏的可以解决吗，试来试去这边还是报泄漏。
