### ISSUE TITLE
viewpager2滑动返回后 csj banner就没了

### ISSUE THREAD

**Issue by HaiSenW** [ifmvo/TogetherAd#34]
**Bug 描述和日志**
viewpager2+fragment左滑后返回 穿山甲的banner广告就没了 过一会才能自动刷新出来
gdt正常
**Bug 复现的步骤**
viewpager2滑动返回

**系统版本以及设备型号**
 - 设备型号：小米11
 - 系统版本：Android11
 - TogetherAd版本：
    5.0.0

**附加信息**

**Comment by ifmvo** [comment]
麻烦提供一个viewpager2+fragment+banner广告的Demo，我再看下

**Comment by ifmvo** [comment]
按理来说，应该只是简单的逻辑控制问题，和广告没关系
