### ISSUE TITLE
gradle4.1.1版本，混淆打包后崩溃，不混淆打包apk运行正常

### ISSUE THREAD

**Issue by matbird** [ifmvo/TogetherAd#36]
gradle4.1.1，创建新项目，依赖方式
   implementation project(':core')
    implementation project(':csj')
    implementation project(':gdt')

最后出现 Direct local .aar file dependencies are not supported 的问题，直接Sync失败

**Comment by ifmvo** [comment]
需要更多的信息，才能排查

**Comment by ifmvo** [comment]
该问题已在5.0.3版本解决
