### ISSUE TITLE
广点通的id就算是随便乱输入都能加载的出来广告

### ISSUE THREAD

**Issue by LiuybDongtt** [ifmvo/TogetherAd#39]
广点通的AppId和广告位的Id随便输入，都能加载的出来，麻烦您看一下

**Comment by ifmvo** [comment]
广点通的appid目前确实可以随便写都有广告，这是广点通它自己的逻辑，我们不清楚也不用去管它，我们只需要照常填写即可。

广告位的ID随便写是一定不能请求到广告的。请检查逻辑是否有误。
