### ISSUE TITLE
希望能使用Service对广告进行缓存

### ISSUE THREAD

**Issue by bobo19870225** [ifmvo/TogetherAd#42]
**你的建议基于你遇到什么问题？**
       由于我们只使用一家平台，有时会拉取失败，我的改进思路是，维护一个广告队列，用服务去拉取，当队列里的广告少于3条时就去拉取，相当于做了一个公共的广告池。尴尬的是，AdHelperXXX类需要传入Activity，这是不是就是说如果要做缓存只能针对单个页面？是否可以做一个全局的广告池？

**你希望怎样改进？**
希望能够实现广告的全局缓存

**Comment by ifmvo** [comment]
1. 首先这种思路，会极大的浪费广告，对ecpm的负面影响可能要超过缓存广告带来的填充率增量。
2. 并不是AdHelperXXX类需要传入Activity，而是广告提供商需要传Activity。
3. 除非特殊项目，开屏广告和激励广告一般整个APP中也就展示一次，而且有的广告提供商并不会返回广告实体。
4. 原生自渲染和原生模板可以自行尝试按照这个思路来做，但是这两种广告类型价格都偏低，优化空间不大，而且最好向相应广告提供商咨询是否可行。
