### ISSUE TITLE
合规问题

### ISSUE THREAD

**Issue by bobo19870225** [ifmvo/TogetherAd#44]
最近上架华为被检测出在用户接受协议前收集设备信息的问题，原因是广告SDK在启动时初始化，没等用户接受协议就去获取设备信息了，能否封装成友盟SDK一样的模式：先“预初始化”，等用户接受后再调真正的初始化，此时再去获取设备信息。

**Comment by ifmvo** [comment]
不需要预初始化，就用户接收后再初始化就行了。
