### ISSUE TITLE
开屏广告请求与展示分开的示例可否更加具体一点，体现不出在实际应用中的使用

### ISSUE THREAD

**Issue by easytome** [ifmvo/TogetherAd#45]
**你的建议基于你遇到什么问题？**
开屏广告请求与展示分开的示例可否更加具体一点，体现不出在实际应用中的使用

**你希望怎样改进？**
我理解请求和展示分开是可以用来预加载，但是看到AdHelperSplashPro中传入了Activity引用，感觉不能用于预加载
我想问可以持有一个单例，在开屏页面展示的时候先请求，下次进入另一个activity再展示，达到预加载的效果吗

**Comment by ifmvo** [comment]
提供商要求必须传activity，目前的预加载设计初衷是：如果Splashactivity展示广告之前如果有耗时任务，可以在当前activity预加载

至于你说的单例，这种逻辑之前的版本试过，会有一个问题：无法同时请求多个广告。

还有就是，如果实现在不同页面之间实现预加载，会出现广告大量浪费的问题。算起来，这种预加载带来的优化性价比并不好。
