### ISSUE TITLE
快手信息流广告，还没实现吗？

### ISSUE THREAD

**Issue by PopFisher** [ifmvo/TogetherAd#49]
快手信息流广告，还没实现吗？

abstract class KsProviderNativeExpress : KsProviderNative() {

    override fun getNativeExpressAdList(activity: Activity, adProviderType: String, alias: String, adCount: Int, listener: NativeExpressListener) {
        callbackNativeExpressStartRequest(adProviderType, alias, listener)
       // 这里怎么直接就调用失败了？
        callbackNativeExpressFailed(adProviderType, alias, listener, null, activity.getString(R.string.ks_can_not))
    }

    override fun destroyNativeExpressAd(adObject: Any) {
        
    }

    override fun nativeExpressAdIsBelongTheProvider(adObject: Any): Boolean {
        return false
    }
}

**Comment by ifmvo** [comment]
5.1.1版本开始支持
