### ISSUE TITLE
快手视频广告show方法永远返回false

### ISSUE THREAD

**Issue by PopFisher** [ifmvo/TogetherAd#51]
类：KsProviderReward  中 showRewardAd 返回false

 override fun showRewardAd(activity: Activity): Boolean {
        if (rewardVideoAd?.isAdEnable == true) {
            val config = KsVideoPlayConfig.Builder()
                    .showLandscape(KsProvider.Reward.isShowLandscape)
                    .build()
            rewardVideoAd!!.showRewardVideoAd(activity, config)
        }
        return false
    }

**Comment by ifmvo** [comment]
5.1.5以上版本已解决
