### ISSUE TITLE
这四家厂商开屏广告ecpm排名是怎样的？

### ISSUE THREAD

**Issue by hukejia** [ifmvo/TogetherAd#54]

**Comment by hukejia** [comment]
> 都接进去试一下咯，目前我这边发现的是 头条的开屏比广点通的高，快手还待验证，百度听说不好就没接

感觉就穿山甲和广电通能用了，快手测试开屏填充约等于0，开屏基本全部出不来，百度还没试

**Comment by ifmvo** [comment]
各种因素影响，没有绝对的排名喔！自己试了才知道。
