### ISSUE TITLE
建议拓展展示机制

### ISSUE THREAD

**Issue by loperSeven** [ifmvo/TogetherAd#57]
现有：权重机制
比如：竞价机制（同时获取N家平台广告，单价最高的展示）、响应速度机制（同时获取N家平台，响应最快的展示）

**Comment by ifmvo** [comment]
同时获取多家广告的方法不可取，浪费广告导致的ecpm下降的损失>竞价机制带来的增量

**Comment by loperSeven** [comment]
> 同时获取多家广告的方法不可取，浪费广告导致的ecpm下降的损失>竞价机制带来的增量

现在很多平台都推出了竞价机制呀，如果不同时请求如何竞价呢
