### ISSUE TITLE
预加载广告

### ISSUE THREAD

**Issue by lmDai** [ifmvo/TogetherAd#65]
**你的建议基于你遇到什么问题？**

开屏页广告没有预加载功能，会影响页面展示效果
**你希望怎样改进？**
加入预加载功能，有缓存直接加载缓存

**Comment by ifmvo** [comment]
开屏有预加载，请看文档。

**Comment by ifmvo** [comment]
https://github.com/ifmvo/TogetherAd/blob/master/demo/src/main/java/com/ifmvo/togetherad/demo/splash/SplashProActivity.kt
